<?php
$products = $this->getRecommended();
?>
<!-- slider big -->
<script type="text/javascript">
    $(window).load(function() {
        $('#slider').nivoSlider();
    });
</script>
<div id="baner">
    <div id="slider" class="nivoSlider">
        <?php if (is_array($products) && count($products)) { ?>
            <?php foreach ($products as $product) { ?>
                <img src="<?php echo $product['img'] ?>" alt="" />
            <?php } ?>
        <?php } ?>
    </div>
</div>